Stage 19 completed

diff --git a/expl/expl b/expl/expl
--- a/expl/expl
+++ b/expl/expl
@@ -1,8 +1,11 @@
-yacc -d -v abstree.y
-lex abstree.l
-gcc lex.yy.c y.tab.c -w
-./a.out $1
-lex ltranslate.l
-gcc lex.yy.c
-./a.out
-mv assemblycode.xsm $(echo $1 | sed 's/.expl/.xsm/')
+
+#Compiling
+./expl-bin $1
+if [ $? -eq 1 ]
+then
+echo "compilation failed"
+exit 1
+fi
+
+#Label Translation
+./ltranslate
